#!/usr/bin/python

print("Content-type: text/html\n")
print("<html>")
print("<head><title>Script CGI Python</title></head>")
print("<body>")
print("<h1>Bienvenue sur mon script CGI en Python</h1>")
print("<p>Ceci est une page dynamique générée en Python via CGI.</p>")
print("</body>")
print("</html>")
